---
- include: yum.yml
  become: true

- include: java-tools.yml
  become: true
  tags:
    - java-tools

- include: gsearch.yml
  become: true
  tags:
    - gsearch

- include: djatoka.yml
  become: true
  tags:
    - djatoka

- include: islandora.yml
  become: true
  tags: 
    - isla
