; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.50"

; Defaults that apply to all modules.
defaults[projects][type] = "module"
defaults[projects][download][type] = "git"
defaults[projects][download][branch]  = "7.x"
defaults[projects][download][overwrite] = TRUE

; Modules
projects[islandora][download][url] = "https://github.com/Islandora/islandora.git"
projects[islandora_solution_pack_collection][download][url] = "https://github.com/Islandora/islandora_solution_pack_collection.git"
projects[islandora_solution_pack_image][download][url] = "https://github.com/Islandora/islandora_solution_pack_image.git"


; Libraries
libraries[tuque][type] = "library"
libraries[tuque][download][type] = "git"
libraries[tuque][download][url] = "https://github.com/Islandora/tuque.git"
libraries[tuque][download][tag] = "7.x-1.7"


